---

- user:
    name: aur_builder
    group: wheel
- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0600
    validate: 'visudo -cf %s'

- aur:
    name: thelounge
  become: yes
  become_user: aur_builder

- name: copy thelounge config file
  template:
    src: config.js
    dest: /etc/thelounge/config.js
    owner: thelounge
    group: thelounge
    mode: 0644
  notify:
    - restart thelounge

- name: enable and start thelounge
  systemd:
    name: thelounge
    enabled: yes
    state: started
