---

- user:
    name: aur_builder
    group: wheel
- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0600
    validate: 'visudo -cf %s'

- aur:
    name: thelounge
  become: yes
  become_user: aur_builder
